version: "3.9"

services:
  db:
    image: postgres:13
    container_name: pizzabakeren_db
    environment:
      POSTGRES_USER: pizza
      POSTGRES_PASSWORD: pizza
      POSTGRES_DB: pizzabakeren
    ports:
      - "5432:5432"
    volumes:
      - ./database/YEHA.sql:/docker-entrypoint-initdb.d/YEHA.sql
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
